Add test of aes_core module
chipsalliance/UHDM-integration-tests pull request #367
Opened 2021-07-13 11:30 UTC by RRozak

2021-07-13 11:57 UTC, rkapuscik requested changes

2021-07-13 11:57 UTC, rkapuscik commented on tests/opentitan/module_tests/aes_core/main.cpp
> +  while (!Verilated::gotFinish() && (main_time < 100)) {
We're obviously not aiming for a full-fledged testbench here, but try to at least:

1.  Clock the core
2. Bring it out of reset
3. Eyeball the .vcd if the signals seem ok.

2021-07-16 14:10 UTC, rkapuscik approved these changes

2021-08-12 10:59 UTC, RRozak commented
Some errors and warnings can be reproduced by https://github.com/chipsalliance/UHDM-integration-tests/pull/406

2021-08-30 13:42 UTC, RRozak commented
Another errors can be reproduced by: https://github.com/chipsalliance/UHDM-integration-tests/pull/438

2021-10-15 12:02 UTC, RRozak commented
It gives 5 warnings. 2 of them can be reproduced by https://github.com/chipsalliance/UHDM-integration-tests/pull/549

2021-11-19 09:29 UTC, RRozak commented
It gives warning
```%Warning-WIDTH: /home/rrozak/Documents/verilator/uhdm-integration/../uhdm-tests/opentitan/opentitan-current/build`/lowrisc_dv_chip_verilator_sim_0.1/src/lowrisc_ip_aes_0.6/rtl/aes_core.sv:224:9: Operator ASSIGN expects 32 bits on the Assign RHS, but Assign RHS's SEL generates 256 bits.```

2021-12-21 16:12 UTC, RRozak commented
The error can be reproduced by https://github.com/chipsalliance/UHDM-integration-tests/pull/623

2022-01-19 14:54 UTC, merged