Add Parameter2DUnpackedArray test
chipsalliance/UHDM-integration-tests pull request #376
Opened 2021-07-21 11:33 UTC by RRozak

2021-07-22 08:52 UTC, rkapuscik requested changes

2021-07-22 08:52 UTC, rkapuscik commented on tests/Parameter2DUnpackedArray/top.sv
> +                                    '{1, 1, 1}};
Make some of those values different, this will help us check if we pick the right one in the line below.

2021-07-22 09:14 UTC, RRozak commented on tests/Parameter2DUnpackedArray/top.sv
> +                                    '{1, 1, 1}};
Done

2021-07-22 09:15 UTC, rkapuscik approved these changes

2021-07-23 09:05 UTC, rkapuscik commented on tests/LogicPackedArray/top.sv
> +   assign d = x[1][2];
A comment (or even better: assert) with intended output would make it easier to read.

2021-07-23 09:43 UTC, rkapuscik requested changes

2021-07-23 09:43 UTC, rkapuscik commented on tests/ParameterUnpackedArray/top.sv
> +      assert(b == 110;
Typo - missing parenthesis

2021-07-23 09:46 UTC, rkapuscik approved these changes

2021-07-23 09:47 UTC, merged