Add DeclarationInFor test
chipsalliance/UHDM-integration-tests pull request #381
Opened 2021-07-26 14:25 UTC by RRozak

2021-07-26 14:47 UTC, RRozak commented
It waits for https://github.com/chipsalliance/Surelog/issues/1540. It should pass when it is solved.

2021-07-28 07:51 UTC, rkapuscik requested changes

2021-07-28 07:51 UTC, rkapuscik commented on tests/DeclarationInFor/top.sv
> +	 return a;
Fix indentation and it's good to go.

2021-07-28 07:55 UTC, rkapuscik approved these changes

2021-07-28 07:55 UTC, merged