Add IndexedPartSelectInGenscope
chipsalliance/UHDM-integration-tests pull request #623
Opened 2021-12-21 16:11 UTC by RRozak

2021-12-21 16:28 UTC, RRozak commented
It waits for https://github.com/chipsalliance/Surelog/issues/2343

2022-01-18 16:02 UTC, RRozak commented
It is passed by current verilator.

2022-01-18 16:33 UTC, rkapuscik requested changes

2022-01-18 16:33 UTC, rkapuscik commented on tests/IndexedPartSelectInFor/top.sv
> +      for (int i = 0; i < NumRegsKey; i++) begin
Maybe keep `NumRegsKey` lower here, otherwise we end up accessing invalid range below.

2022-01-19 14:11 UTC, RRozak commented on tests/IndexedPartSelectInFor/top.sv
> +      for (int i = 0; i < NumRegsKey; i++) begin
Done

2022-01-19 14:19 UTC, rkapuscik approved these changes

2022-01-19 14:34 UTC, merged